language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.3

env:
  global:
    - DB=pgsql
  matrix:
    - MOODLE_BRANCH=MOODLE_35_STABLE
    - MOODLE_BRANCH=MOODLE_36_STABLE
    - MOODLE_BRANCH=MOODLE_37_STABLE
    - MOODLE_BRANCH=master

matrix:
  include:
    # Test older Moodles only with PHP 7.1
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_37_STABLE
    # Test with MySQL
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=master
    # Test with PHP 7.3
    - php: 7.3
      env: MOODLE_BRANCH=master

before_install:
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci validate
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat